// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// source: determined/api/v1/submission.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How the master admits a submitted job to the scheduler.
type Admission int32

const (
	// The default, which queues the job like ADMISSION_QUEUE.
	Admission_ADMISSION_UNSPECIFIED Admission = 0
	// Queue the job until the scheduler places it.
	Admission_ADMISSION_QUEUE Admission = 1
	// Place the job now or fail it, never queueing it. Experiments reject it.
	Admission_ADMISSION_IMMEDIATE Admission = 2
)

// Enum value maps for Admission.
var (
	Admission_name = map[int32]string{
		0: "ADMISSION_UNSPECIFIED",
		1: "ADMISSION_QUEUE",
		2: "ADMISSION_IMMEDIATE",
	}
	Admission_value = map[string]int32{
		"ADMISSION_UNSPECIFIED": 0,
		"ADMISSION_QUEUE":       1,
		"ADMISSION_IMMEDIATE":   2,
	}
)

func (x Admission) Enum() *Admission {
	p := new(Admission)
	*p = x
	return p
}

func (x Admission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Admission) Descriptor() protoreflect.EnumDescriptor {
	return file_determined_api_v1_submission_proto_enumTypes[0].Descriptor()
}

func (Admission) Type() protoreflect.EnumType {
	return &file_determined_api_v1_submission_proto_enumTypes[0]
}

func (x Admission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Admission.Descriptor instead.
func (Admission) EnumDescriptor() ([]byte, []int) {
	return file_determined_api_v1_submission_proto_rawDescGZIP(), []int{0}
}

// The admission outcome of a submission.
type AdmissionOutcome int32

const (
	// No outcome, as for a dry run.
	AdmissionOutcome_ADMISSION_OUTCOME_UNSPECIFIED AdmissionOutcome = 0
	// The job was committed and waits in the queue for placement.
	AdmissionOutcome_ADMISSION_OUTCOME_QUEUED AdmissionOutcome = 1
	// The job was committed and placed.
	AdmissionOutcome_ADMISSION_OUTCOME_PLACED AdmissionOutcome = 2
	// The job was committed and then rejected because it could not be placed.
	AdmissionOutcome_ADMISSION_OUTCOME_REJECTED AdmissionOutcome = 3
	// The job was committed, but its placement was not decided in time.
	AdmissionOutcome_ADMISSION_OUTCOME_PENDING AdmissionOutcome = 4
)

// Enum value maps for AdmissionOutcome.
var (
	AdmissionOutcome_name = map[int32]string{
		0: "ADMISSION_OUTCOME_UNSPECIFIED",
		1: "ADMISSION_OUTCOME_QUEUED",
		2: "ADMISSION_OUTCOME_PLACED",
		3: "ADMISSION_OUTCOME_REJECTED",
		4: "ADMISSION_OUTCOME_PENDING",
	}
	AdmissionOutcome_value = map[string]int32{
		"ADMISSION_OUTCOME_UNSPECIFIED": 0,
		"ADMISSION_OUTCOME_QUEUED":      1,
		"ADMISSION_OUTCOME_PLACED":      2,
		"ADMISSION_OUTCOME_REJECTED":    3,
		"ADMISSION_OUTCOME_PENDING":     4,
	}
)

func (x AdmissionOutcome) Enum() *AdmissionOutcome {
	p := new(AdmissionOutcome)
	*p = x
	return p
}

func (x AdmissionOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdmissionOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_determined_api_v1_submission_proto_enumTypes[1].Descriptor()
}

func (AdmissionOutcome) Type() protoreflect.EnumType {
	return &file_determined_api_v1_submission_proto_enumTypes[1]
}

func (x AdmissionOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdmissionOutcome.Descriptor instead.
func (AdmissionOutcome) EnumDescriptor() ([]byte, []int) {
	return file_determined_api_v1_submission_proto_rawDescGZIP(), []int{1}
}

// Options for submitting a managed command, shell, generic task, or experiment.
type SubmitOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A key that makes the submission idempotent for its owner: a request with a
	// key the owner already used returns that job instead of creating one. At
	// most 128 characters of [A-Za-z0-9._:-].
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// How the job is admitted to the scheduler.
	Admission Admission `protobuf:"varint,2,opt,name=admission,proto3,enum=determined.api.v1.Admission" json:"admission,omitempty"`
	// Check the request and return its digest without creating anything.
	DryRun bool `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// The request digest a dry run returned. The request fails with
	// FAILED_PRECONDITION and reason plan_changed, creating nothing, if its
	// digest differs.
	ExpectedDigest string `protobuf:"bytes,4,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
}

func (x *SubmitOptions) Reset() {
	*x = SubmitOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_determined_api_v1_submission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOptions) ProtoMessage() {}

func (x *SubmitOptions) ProtoReflect() protoreflect.Message {
	mi := &file_determined_api_v1_submission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOptions.ProtoReflect.Descriptor instead.
func (*SubmitOptions) Descriptor() ([]byte, []int) {
	return file_determined_api_v1_submission_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOptions) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SubmitOptions) GetAdmission() Admission {
	if x != nil {
		return x.Admission
	}
	return Admission_ADMISSION_UNSPECIFIED
}

func (x *SubmitOptions) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *SubmitOptions) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

// The result of submitting a managed command, shell, generic task, or
// experiment.
type SubmitResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the job, empty for a dry run.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Whether the request replayed a job submitted earlier with the same
	// idempotency key.
	Replayed bool `protobuf:"varint,2,opt,name=replayed,proto3" json:"replayed,omitempty"`
	// The digest of the request, which identifies its content. Clients treat it
	// as opaque.
	RequestDigest string `protobuf:"bytes,3,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`
	// The admission outcome of the job.
	Outcome AdmissionOutcome `protobuf:"varint,4,opt,name=outcome,proto3,enum=determined.api.v1.AdmissionOutcome" json:"outcome,omitempty"`
}

func (x *SubmitResult) Reset() {
	*x = SubmitResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_determined_api_v1_submission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResult) ProtoMessage() {}

func (x *SubmitResult) ProtoReflect() protoreflect.Message {
	mi := &file_determined_api_v1_submission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResult.ProtoReflect.Descriptor instead.
func (*SubmitResult) Descriptor() ([]byte, []int) {
	return file_determined_api_v1_submission_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitResult) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

func (x *SubmitResult) GetRequestDigest() string {
	if x != nil {
		return x.RequestDigest
	}
	return ""
}

func (x *SubmitResult) GetOutcome() AdmissionOutcome {
	if x != nil {
		return x.Outcome
	}
	return AdmissionOutcome_ADMISSION_OUTCOME_UNSPECIFIED
}

var File_determined_api_v1_submission_proto protoreflect.FileDescriptor

var file_determined_api_v1_submission_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x64,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0xb6, 0x01, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65,
	0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b,
	0x65, 0x79, 0x12, 0x3a, 0x0a, 0x09, 0x61, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x65, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x09, 0x61, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17,
	0x0a, 0x07, 0x64, 0x72, 0x79, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x64, 0x72, 0x79, 0x52, 0x75, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74,
	0x22, 0xa7, 0x01, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x6f,
	0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x64,
	0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d,
	0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x2a, 0x54, 0x0a, 0x09, 0x41, 0x64,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x44, 0x4d, 0x49, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x44, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f,
	0x51, 0x55, 0x45, 0x55, 0x45, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x44, 0x4d, 0x49, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x49, 0x4d, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x54, 0x45, 0x10, 0x02,
	0x2a, 0xb0, 0x01, 0x0a, 0x10, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x75,
	0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x1d, 0x41, 0x44, 0x4d, 0x49, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x44, 0x4d, 0x49,
	0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x51, 0x55,
	0x45, 0x55, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x44, 0x4d, 0x49, 0x53, 0x53,
	0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x43,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x44, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f,
	0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x44, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f,
	0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x10, 0x04, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x64, 0x2d, 0x61, 0x69, 0x2f,
	0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_determined_api_v1_submission_proto_rawDescOnce sync.Once
	file_determined_api_v1_submission_proto_rawDescData = file_determined_api_v1_submission_proto_rawDesc
)

func file_determined_api_v1_submission_proto_rawDescGZIP() []byte {
	file_determined_api_v1_submission_proto_rawDescOnce.Do(func() {
		file_determined_api_v1_submission_proto_rawDescData = protoimpl.X.CompressGZIP(file_determined_api_v1_submission_proto_rawDescData)
	})
	return file_determined_api_v1_submission_proto_rawDescData
}

var file_determined_api_v1_submission_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_determined_api_v1_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_determined_api_v1_submission_proto_goTypes = []interface{}{
	(Admission)(0),        // 0: determined.api.v1.Admission
	(AdmissionOutcome)(0), // 1: determined.api.v1.AdmissionOutcome
	(*SubmitOptions)(nil), // 2: determined.api.v1.SubmitOptions
	(*SubmitResult)(nil),  // 3: determined.api.v1.SubmitResult
}
var file_determined_api_v1_submission_proto_depIdxs = []int32{
	0, // 0: determined.api.v1.SubmitOptions.admission:type_name -> determined.api.v1.Admission
	1, // 1: determined.api.v1.SubmitResult.outcome:type_name -> determined.api.v1.AdmissionOutcome
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_determined_api_v1_submission_proto_init() }
func file_determined_api_v1_submission_proto_init() {
	if File_determined_api_v1_submission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_determined_api_v1_submission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_determined_api_v1_submission_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_determined_api_v1_submission_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_determined_api_v1_submission_proto_goTypes,
		DependencyIndexes: file_determined_api_v1_submission_proto_depIdxs,
		EnumInfos:         file_determined_api_v1_submission_proto_enumTypes,
		MessageInfos:      file_determined_api_v1_submission_proto_msgTypes,
	}.Build()
	File_determined_api_v1_submission_proto = out.File
	file_determined_api_v1_submission_proto_rawDesc = nil
	file_determined_api_v1_submission_proto_goTypes = nil
	file_determined_api_v1_submission_proto_depIdxs = nil
}
